-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 16:44:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db-laGranjita
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-laGranjita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-laGranjita` DEFAULT CHARACTER SET utf8 ;
USE `db-laGranjita` ;

-- -----------------------------------------------------
-- Table `db-laGranjita`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-laGranjita`.`Empleados` (
  `idEmpleados` INT NOT NULL,
  `nombreEmpleado` VARCHAR(45) NULL,
  `apellidoEmpleado` VARCHAR(45) NULL,
  `telefonoEmpleado` INT NULL,
  `direccionEmpleado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-laGranjita`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-laGranjita`.`Productos` (
  `idProductos` INT NOT NULL,
  `nombreProduc` VARCHAR(45) NULL,
  `tipoProduc` VARCHAR(45) NULL,
  `unidadMediadProduc` VARCHAR(45) NULL,
  `costoProduc` DOUBLE NULL,
  `cantidadPro` INT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-laGranjita`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-laGranjita`.`Clientes` (
  `idClientes` INT NOT NULL,
  `nombreCliente` VARCHAR(45) NULL,
  `ApellidoCliente` VARCHAR(45) NULL,
  `edadCliente` INT NULL,
  `telefonoCliente` INT NULL,
  `direccionCliente` VARCHAR(45) NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-laGranjita`.`Facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-laGranjita`.`Facturas` (
  `idFacturas` INT NOT NULL,
  `fechaFactura` VARCHAR(45) NULL,
  `Productos_idProductos` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idFacturas`),
  INDEX `fk_Facturas_Productos1_idx` (`Productos_idProductos` ASC),
  INDEX `fk_Facturas_Clientes1_idx` (`Clientes_idClientes` ASC),
  CONSTRAINT `fk_Facturas_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `db-laGranjita`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `db-laGranjita`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-laGranjita`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-laGranjita`.`Ventas` (
  `idVentas` INT NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  `Facturas_idFacturas` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idVentas`),
  INDEX `fk_Ventas_Empleados1_idx` (`Empleados_idEmpleados` ASC),
  INDEX `fk_Ventas_Facturas1_idx` (`Facturas_idFacturas` ASC),
  INDEX `fk_Ventas_Clientes1_idx` (`Clientes_idClientes` ASC),
  INDEX `fk_Ventas_Productos1_idx` (`Productos_idProductos` ASC),
  CONSTRAINT `fk_Ventas_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `db-laGranjita`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Facturas1`
    FOREIGN KEY (`Facturas_idFacturas`)
    REFERENCES `db-laGranjita`.`Facturas` (`idFacturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `db-laGranjita`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `db-laGranjita`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-laGranjita`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-laGranjita`.`Categorias` (
  `idCategorias` INT NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idCategorias`),
  INDEX `fk_Categorias_Empleados_idx` (`Empleados_idEmpleados` ASC),
  CONSTRAINT `fk_Categorias_Empleados`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `db-laGranjita`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-laGranjita`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-laGranjita`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `Usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_Empleados1_idx` (`Empleados_idEmpleados` ASC),
  CONSTRAINT `fk_Usuarios_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `db-laGranjita`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
